name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          extended: true
          hugo-version: '0.152.2'
      - name: Build Site
        run: hugo
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        env:
          WRANGLER_SEND_METRICS: false
        with:
          wranglerVersion: '4.43.0'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}